inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - "bin/*"
    - "vendor/**/*"
    - "Dangerfile"
    - "Guardfile"
    - "Gemfile"
    - "spec/postal_code/**/*"
    - "data/*"
    - "db/**/*"
