default: &default
  adapter:  postgis
  pool:    5
  timeout: 5000
  host:     <% ENV["DATABASE_HOST"] %>
  username: <% ENV["DATABASE_USERNAME"] %>
  password: <% ENV["DATABASE_PASSWORD"] %>
  database: <% ENV["DATABASE_NAME"] %>

production:
  <<: *default

development:
  <<: *default
  database: postalcode_development

test:
  <<: *default
  database: postalcode_test
